# TODO: fill in Dockerfile to run message.py script

# Set runtime / base image 
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy python script
COPY message.py .

# Run script
CMD ["python", "message.py"]